### ISSUE TITLE
GitLab connectors missing Base class dependency

### ISSUE THREAD

**Issue by stevencoulter** [authomize/Open-ITDR#34]
The connectors from the GitLab [Authomize Repository](https://gitlab.com/gitlab-com/gl-security/engineering-and-research/automation-team/authomize/-/tree/main/connectors) which have been copied over to the [Open-ITDR/Connectors](https://github.com/authomize/Open-ITDR/tree/main/Open-Connectors) folder extend from a [Base](https://github.com/authomize/Open-ITDR/blob/d24e1ef8bc837a860e9028989a9fe1b302eef75c/Open-Connectors/ava-tax/ava_tax.py#L18) class defined in [connectors/__init__.py](https://gitlab.com/gitlab-com/gl-security/engineering-and-research/automation-team/authomize/-/blob/main/connectors/__init__.py#L108) in the GitLab Repository.  That base class is not available in this repository, but should be if we want to run the connectors from here.

**Comment by sriley0975** [comment]
Thanks for the update we will look unto this - appreciate the details.

**Comment by sriley0975** [comment]
replicated repo as is - should work with base class now available [at](https://github.com/authomize/Open-ITDR/blob/main/Open-Connectors/Connectors/GitLab-Authomize-Connectors/GitLab-Authomize/connectors/__init__.py)
