### ISSUE TITLE
GitLab connectors missing execution script

### ISSUE THREAD

**Issue by stevencoulter** [authomize/Open-ITDR#35]
The connectors from the GitLab [Authomize Repository](https://gitlab.com/gitlab-com/gl-security/engineering-and-research/automation-team/authomize/-/tree/main/connectors) which have been copied over to the [Open-ITDR/Connectors](https://github.com/authomize/Open-ITDR/tree/main/Open-Connectors) folder are meant to be executed via the [main.py](https://gitlab.com/gitlab-com/gl-security/engineering-and-research/automation-team/authomize/-/blob/main/main.py) script found in the GitLab Repository, but should be available if we want to run the connectors from here.

**Comment by sriley0975** [comment]
Thanks Steve - probably makes sense to do that here too - I'll speak to to the person doing these and see about getting the updates done.

**Comment by sriley0975** [comment]
Available on repository [here](https://github.com/authomize/Open-ITDR/blob/main/Open-Connectors/Connectors/GitLab-Authomize-Connectors/GitLab-Authomize/main.py) now
