### ISSUE TITLE
GitLab connectors missing build environment

### ISSUE THREAD

**Issue by stevencoulter** [authomize/Open-ITDR#36]
The connectors from the GitLab [Authomize Repository](https://gitlab.com/gitlab-com/gl-security/engineering-and-research/automation-team/authomize/-/tree/main/connectors) which have been copied over to the [Open-ITDR/Connectors](https://github.com/authomize/Open-ITDR/tree/main/Open-Connectors) are missing the build environment that was originally provided by GitLab.  The GitLab repository includes a [Dockerfile](https://gitlab.com/gitlab-com/gl-security/engineering-and-research/automation-team/authomize/-/blob/main/Dockerfile), [Makefile](https://gitlab.com/gitlab-com/gl-security/engineering-and-research/automation-team/authomize/-/blob/main/Makefile), [PipFile](https://gitlab.com/gitlab-com/gl-security/engineering-and-research/automation-team/authomize/-/blob/main/Pipfile), and [sample.env](https://gitlab.com/gitlab-com/gl-security/engineering-and-research/automation-team/authomize/-/blob/main/sample.env) which provide a nice environment for building and running the connectors.  There is no such environment provided in the Open-ITDR repository.

The ability to run the GitLab connectors from Open-ITDR also depends on issues #34 and #35

**Comment by sriley0975** [comment]
Yes - agreed - we need this - I have it on my list of "things to do" - another backlog item - Will bubble this up and see about getting this implemented - thanks for the feedback your exactly right.

**Comment by sriley0975** [comment]
Files available [here](https://github.com/authomize/Open-ITDR/tree/main/Open-Connectors/Connectors/GitLab-Authomize-Connectors/GitLab-Authomize)
