### ISSUE TITLE
GitLab connectors including incorrect namespace

### ISSUE THREAD

**Issue by stevencoulter** [authomize/Open-ITDR#37]
The connectors from the GitLab [Authomize Repository](https://gitlab.com/gitlab-com/gl-security/engineering-and-research/automation-team/authomize/-/tree/main/connectors) which have been copied over to the [Open-ITDR/Connectors](https://github.com/authomize/Open-ITDR/tree/main/Open-Connectors) folder are including the `authomize.rest_api_client.generated.schemas` namespace but should be including the `authomize.rest_api_client.generated.connectors_rest_api.schemas` namespace from the [connectors-rest-api-client](https://github.com/authomize/connectors-rest-api-client/blob/master/authomize/rest_api_client/generated/connectors_rest_api/schemas.py) repository.

**Comment by sriley0975** [comment]
Appreciate you doing this - thank you.
